<a href="https://colab.research.google.com/github/rezaAdinepour/Linear-Algebra/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font face="Calibri" size=5><div dir=rtl align=center>
<font face="IranNastaliq" size=5>
به نام خدا
</font>
<br>
<font size=3>
دانشگاه صنعتی شاهرود - دانشکده مهندسی برق
</font>
<br>
<font color=blue size=5>
جبر خطی
</font>

<hr/>
<font color=red size=6>
فصل اول: مروری بر پایتون و مباحث پایه ای
<br>
جبرخطی
<br>
</font>
استاد درس: جناب آقای دکتر جواد کیقبادی
<br>
تهیه کننده: رضا آدینه پور
<hr>
</div></font>

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>1. پایتون</font>
<br>
در این قسمت مرور سریعی بر پایتون داریم
</div></font>

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>1.1 فراخوانی کتابخانه های مورد نیاز</font>
<br>
بدون شک، مهمترین کتابخانه ای که برای محاسبات ماتریسی در پایتون وجود دارد، numpy و sympy است

</div></font>

In [5]:
import numpy as np  # or import numpy
import sympy as sp

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>1.2 چاپ اطلاعات و دریافت ورودی از کاربر</font>
<br>
دقت شود که خروجی تابع input، رشته است
<br>
برای تبدیل رشته به عدد integer، از تابع ()int استفاده میکنیم.

</div></font>

In [ ]:
id_str = input('enter your student id: ')
print(id_str)
print(type(id_str))

id_int = int(id_str)
print(type(id_int))

enter your student id: 9814303
9814303
<class 'str'>
9814303
<class 'int'>


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2. جبرخطی</font>
<br>
در اینجا به یادآوری کوتاهی از جبرخطی در راستای اهداف درس می پردازیم
</div></font>

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.1. بردارها و فضای برداری</font>
<br>
به یک n تایی به صورت
$X = [x_1, x_2, ⋯ , x_n]$
یک 
<b>بردار سطری</b>
 گفته می شود و می گوییم X یک بردار 
$1 × n$
است.
<br>
مشابها یک n تایی به صورت
$Y = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}
$
<b>بردار ستونی</b>
$n \times 1$
است.
<br>
در ادامه به عنوان مثال بردارهای ستونی و سطری تولید می کنیم و شیوه دسترسی به المان
آن‎ها
را نشان می دهیم.

یک بردار به طور کلی به صورت زیر تعریف می شود:
</div></font>

In [ ]:
import numpy as np
X = np.array( [1, 5, 4] )[np.newaxis]
Y = np.array( [ [1], [5], [4] ] )
XT = X.T # or X.transpose()
print(X)
print('shape of vector X: {}' .format(X.shape))
print(Y)  
print('shape of vector Y: {}' .format(Y.shape))
print(XT)
print('shape of vector XT: {}' .format(Y.shape))

[[1 5 4]]
shape of vector X: (1, 3)
[[1]
 [5]
 [4]]
shape of vector Y: (3, 1)
[[1]
 [5]
 [4]]
shape of vector XT: (3, 1)


<font face="Calibri" size=4><div dir=rtl>
<br>
برای تولید یک دنباله با قدر نسبت مشخص می توان به صورت زیر عمل کرد
</div></font>

In [ ]:
a = np.arange(1, 2, 0.1) #np.arange(lower limit, upper limit, step)
print(a)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
(10,)


<font face="Calibri" size=4><div dir=rtl>
<br>
دسترسی به المان های یک بردار به صورت زیر انجام میشود
<br>
برخلاف متلب، در پایتون اندیس ها از صفر شروع میشود

</div></font>

In [ ]:
X = np.array([1, 5, 10, 15])
print('first element: {}' .format(X[0]))
print('second element: {}' .format(X[1]))
print('last element: {}' .format(X[-1]))

first element: 1
second element: 5
last element: 15


<font face="Calibri" size=4><div dir=rtl>

یک 
<b>فضای برداری</b>
 مجموعه ای مانند
$S$
است که عناصر آن بردار هستند. اعمال جمع و ضرب اسکالری برای این عناصر تعریف می شود که در شرایط ذیل صدق می کنند.(
$U$
،
$V$
و 
$W$
عناصر دلخواه
$S$
،
$c$
و
$d$
اسکالر هستند)

1. حاصل جمع U + V وجود دارد و متعلق به S است.( S تحت جمع بسته است)

2. $cU$
    عنصری از S است.(S تحت ضرب اسکالر بسته است.)

3. $U+V=V+U$
    (ویژگی جابجایی)

4. $U+(V+W)=(U+V)+W$
    (ویژگی شرکت پذیری)

5. عنصری از
    V،
    که بردار صفر نامیده می شود، با
    0
  نشان داده می شود، وجود دارد به قسمی که
  $U+0=U$

6. متناظر هر عنصر U از S عنصری وجود دارد که قرینه U نامیده و با U− نشان داده می شود به قسمی که:
$$U+(-U)=0$$

7. $ⅽ(U + V) = ⅽU + ⅽV$

8. $(ⅽ + ⅾ)U = ⅽU + ⅾU$

9. $ⅽ(ⅾU) = (ⅽⅾ)U$

10. $۱U = U$

فضاهای برداری می توانند شامل فضاهای برداری دیگری نیز باشند. اگر
$V$
یک فضای برداری باشد آنگاه
$S \subseteq V$
یک 
<b>زیرفضای</b>
 V نامیده می شود اگر:

1. $0 \in S$
2. S تحت جمع بسته باشد:
$x,y \in S ⇒ x+y \in S$
3. S تحت ضرب اسکالر بسته باشد:
$x \in S, α \in \mathbf{R} ⇒ αS \in S$

به عنوان مثال یک خط که از مبدا می گذرد زیر فضای 
$R^2$
است.

فرض کنیم
$V_1,V_2,\cdots,V_m$
بردارهایی در فضای برداری S باشند. گوییم
$V$،
برداری در
$S$،
یک 
<b>ترکیب خطی</b>
 از
$V_1,V_2,\cdots,V_m$
است هرگاه اسکالرهایی چون
$c_1,c_2,\cdots,c_m$
موجود باشند به قسمی که V را بتوان چنین نوشت:
$$V=c_1V_1+c_2V_2+\cdots+c_mV_m$$

مجموعه بردارهای
$V_1,V_2,\cdots,V_m$
از یک فضای برداری را وقتی یک 
<b>مولد</b>
 این فضا می نامیم که هر بردار فضا ترکیبی از این بردارها باشد. یک مجموعه مولد از بردارها به یک معنی فضای برداری مربوطه را معرفی می کند زیر هر بردار آن فضا را می توان از این بردار ها بدست آورد.

مجموعه بردارهای
${V_1,V_2,\cdots,V_n}$
را 
<b>مستقل خطی</b>
 گوییم هرگاه از معادله
$$c_1V_1+c_2V_2+\cdots+c_nV_n=0\qquad(1)$$
نتیجه شود که
$$c_1=c_2=\cdots=c_n=0$$
چنانچه حداقل یک
$c_i\neq0$
وجود داشته باشد که معادله (1) برقرار باشد گوییم مجموعه بردارهای
${V_1,V_2,\cdots,V_n}$
وابسته خطی هستند.

مجموعه ای متناهی از بردارها مانند
$\lbrace V_1,\cdots,V_m \rbrace$
را یک 
<b>پایه</b>
 فضای برداری
$S$
نامیم هرگاه این مجموعه مولد
$S$
و مستقل خطی باشد.

<b>مثال)</b>
آیا بردارهای
$\lbrace (1,-1,1),(-1,-1,1),(0,1,1) \rbrace$
برای
$\mathbf{R}^3$
پایه هستند؟


<b>حل)</b>

اسکالرهای
$c_1,c_2,c_3$
باید وجود داشته باشند که
$$c_1(1,-1,1)+c_2(-1,-1,1)+c_3(0,1,1)=(x_1,x_2,x_3)$$
\begin{equation*}
\Rightarrow
\begin{cases}
c_1-c_2=x_1 \\
-c_1-c_2+c_3=x_2 \\
c_1+c_2+c_3=x_3
\end{cases}
\Rightarrow
\begin{cases}
c_1=\frac{2x_1-x_2+x_3}{4} \\
c_2=\frac{-2x_1-x_2+x_3}{4} \\
c_3=\frac{x_2+x_3}{2}
\end{cases}
\end{equation*}
اکنون مستقل خطی بودن را بررسی می کنیم
$$b_1(1,-1,1)+b_2(-1,-1,1)+b_3(0,1,1)=0$$
\begin{equation*}
\Rightarrow
\begin{cases}
b_1-b_2=0 \\
-b_1-b_2+b_3=0 \\
b_1+b_2+b_3=0
\end{cases}
\qquad\Rightarrow
b_1=b_2=b_3=0
\end{equation*}
پس این مجموعه بردارها پایه
$\mathbf{R}^3$
هستند.

</div></font>

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.2. ماتریس‎ها</font>
<br>
یک ماتریس مجموعه ای از بردارها است مثلا اگر
$$
A=
\begin{bmatrix}
1 & 2 & 9\\
0 & -1 & 6\\
1 & 2 & 7\\
\end{bmatrix}_{3\times 3},\qquad
B=
\begin{bmatrix}
1 & 1\\
1 & 1\\
\end{bmatrix}_{2\times 2}
$$
$$
C=
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}_{2\times 3},\qquad
D=
\begin{bmatrix}
1 & 9\\
-1 & 0\\
2 & 6\\
\end{bmatrix}_{3\times 2}
$$
آنگاه:
	
A ماتریسی است که 3 سطر و 3 ستون دارد

B ماتریسی است که 2 سطر و 2 ستون دارد

C ماتریسی است که 2 سطر و 3 ستون دارد

D ماتریسی است که 3 سطر و 2 ستون دارد

<br>
در ادامه یک نمونه ماتریس تولید می کنیم.
</div></font>

In [ ]:
A = np.array([ [1, 5, 8],
               [5, 7, 9], 
               [10, 41, 73] ])

print(A)
print(A.shape)

[[ 1  5  8]
 [ 5  7  9]
 [10 41 73]]
(3, 3)


<font face="Calibri" size=4><div dir=rtl>
<br>
می توان بردار ها را به ماتریس تبدیل کرد
</div></font>

In [ ]:
A = np.arange(6)
print(A)
print(A.shape)
B = A.reshape(2, 3)
print(B)
print(B.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]
(2, 3)


<font face="Calibri" size=4><div dir=rtl>

<b>ترانهاده</b>
 ماتریس A را با
$A^T$
نمایش می دهیم که از جابجایی سطرها و ستون‎های آن ایجاد می شود پس اگر
$$
A=
\begin{bmatrix}
1&3&6 \\
7&2&-4 \\
\end{bmatrix}
$$
آنگاه
$$
A^T=
\begin{bmatrix}
1&7 \\
3&2 \\
6&-4 \\
\end{bmatrix}
$$

در ادامه برابری ترانهاده یک ماتریس متقارن با خودش را بررسی می کنیم
</div></font>

In [ ]:
A = np.array([ [1, 2, 3],
               [2, 0, 4], 
               [3, 4, 5] ])
print(A)
print('-'*10)
print(A.T)
print('-'*10)
print(A == A.T)

[[1 2 3]
 [2 0 4]
 [3 4 5]]
----------
[[1 2 3]
 [2 0 4]
 [3 4 5]]
----------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.3 ماتریس های مختلط</font>
<br>
</div></font>

In [ ]:
a = np.array([ [4+10j, 2, 7],
               [4-2j, -1j, -1+3j],
               [1, 7, 0] ])

a_absolute = np.abs(a)
a_angle = np.angle(a)
a_conjugate = np.conj(a)
a_real = np.real(a)
a_imag = np.imag(a)

print('matrix A: ')
print(a)
print('-'*50)

print('Absolute of A: ')
print(a_absolute)
print('-'*50)

print('Angle A(in radian): ')
print(a_angle) #in radian
print('-'*50)

print('Angle A(in degree): ')
print(a_angle * 180/np.pi) #in degre
print('-'*50)

print('conjugate of A:')
print(a_conjugate)
print('-'*50)

print('Real part of A:')
print(a_real)
print('-'*50)

print('Imaginary part of A:')
print(a_imag)
print('-'*50)


matrix A: 
[[ 4.+10.j  2. +0.j  7. +0.j]
 [ 4. -2.j -0. -1.j -1. +3.j]
 [ 1. +0.j  7. +0.j  0. +0.j]]
--------------------------------------------------
Absolute of A: 
[[10.77032961  2.          7.        ]
 [ 4.47213595  1.          3.16227766]
 [ 1.          7.          0.        ]]
--------------------------------------------------
Angle A(in radian): 
[[ 1.19028995  0.          0.        ]
 [-0.46364761 -1.57079633  1.89254688]
 [ 0.          0.          0.        ]]
--------------------------------------------------
Angle A(in degree): 
[[ 68.19859051   0.           0.        ]
 [-26.56505118 -90.         108.43494882]
 [  0.           0.           0.        ]]
--------------------------------------------------
conjugate of A:
[[ 4.-10.j  2. -0.j  7. -0.j]
 [ 4. +2.j -0. +1.j -1. -3.j]
 [ 1. -0.j  7. -0.j  0. -0.j]]
--------------------------------------------------
Real part of A:
[[ 4.  2.  7.]
 [ 4. -0. -1.]
 [ 1.  7.  0.]]
--------------------------------------------------
Im

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.4 جمع ماتریسها</font>
<br>
</div></font>

In [ ]:
a = np.array([ [1, 2],
               [2, 3] ])
b1 = np.array([3])
b2 = np.array([4, 5])[np.newaxis]

print(a+b1)
print('-'*10)
print(a+b2)
print('-'*10)
print(a+b2.T)

[[4 5]
 [5 6]]
----------
[[5 7]
 [6 8]]
----------
[[5 6]
 [7 8]]


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.5 ضرب ماتریسها</font>
<br>
ضرب ماتریسی، مشابه با عملگر * در متلب
</div></font>

In [ ]:
A = np.array([ [1, 2, 3],
               [2, 0, 4], 
               [3, 4, 5] ])
B = np.array([2, 7, 15])[np.newaxis].T
C = np.dot(A, B)
print(C)

[[ 61]
 [ 64]
 [109]]


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.6 ضرب درایه به درایه</font>
<br>
مشابه با عملگر *. در متلب
</div></font>

In [ ]:
A = np.array([ [1, 2, 3],
               [2, 0, 4], 
               [3, 4, 5] ])
B = np.array([2, 7, 15])
BB = np.array([2, 7, 15])[np.newaxis].T
C = A * B
CC = A * BB
print(C)
print('-'*10)
print(CC)

[[ 2 14 45]
 [ 4  0 60]
 [ 6 28 75]]
----------
[[ 2  4  6]
 [14  0 28]
 [45 60 75]]


In [ ]:
A = np.array([ [1, 2, 3],
               [2, 0, 4], 
               [3, 4, 5] ])

B = np.array([ [2, 7, 6],
               [4, 7, 9],
               [7, 5, 0] ])
C = A * B
print(C)

[[ 2 14 18]
 [ 8  0 36]
 [21 20  0]]


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>2.7 ضرب داخلی یا Inner Product<br></font>
یکی از اساسی ترین عملیات‎ها در جبرخطی ضرب نقطه ای (Dot Product)
یا ضرب داخلی (Inner Product)
می باشد. فرض کنید
$\mathbf{x}, \mathbf{y} \in \mathbb{R}^d$
در این صورت تعریف می کنیم:
$$\langle \mathbf{x}, \mathbf{y} \rangle = \mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$$

به عبارت دیگر ضرب داخلی روی فضای برداری V تابعی است به فرم
$⟨ .,. ⟩ : \mathbf{V \times V} → \mathbf{R}$
که در شرایط زیر صدق می کند:
1. $⟨ X,X ⟩ ≥ 0$
2. $⟨ X,X ⟩=0 ⇔ X=0$
3. $⟨ X+Y,Z ⟩ = ⟨ X,Z ⟩ + ⟨ Y,Z ⟩$
4. $⟨ α X,Z ⟩ = α ⟨ X,Z ⟩$
5. $⟨ X,Y ⟩ = ⟨ Y,X ⟩$

همانطور که در ادامه می بینیم V یک فضای متریک محسوب می شود.

یکی از کاربردهای ضرب نقطه ای محاسبه میانگین وزن دار است. فرض کنید
$\mathbf{x} \in \mathbb{R}^n,\; \mathbf{w} \in \mathbb{R}^n,\; \sum_{i=1}^{n} {w_i} = 1$ که x بردار مقادیر و w بردار وزن‎های نامنفی مقادیر است در این صورت
$\mathbf{x}^\top \mathbf{w}$
همان میانگین وزن دار است.

مثال:

</div></font>

In [ ]:
x = np.arange(3, dtype=np.float32)
w = np.array([0.5,0.2,0.3])
print(np.dot(x, w)) # method 1
print(np.sum(x * w)) # method 2

0.8
0.8


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>3. دترمینان ماتریس ها</font>
<br>

</div></font>

<font face="XB Zar" size=4><div dir=rtl>

<b>دترمینان</b>
 ماتریس
$2 \times 2$،
A
را با
$det(A)$
نشان داده و به صورت زیر تعریف می کنیم:
$$det \left( 
\begin{bmatrix}
a_{11}&a_{12} \\
a_{21}&a_{22} \\
\end{bmatrix} \right) =
a_{11} a_{22} - a_{12} a_{21}
 $$

<b>کهاد</b>
 درایه
$a_{ij}$
را با
$M_{ij}$
نشان می دهیم و عبارت است از دترمینان ماتریس حاصل از حذف ماتریس
ردیف i
ام و ستون j
ام ماتریس A
.

<b>همسازه</b>
 درایه
$a_{ij}$
را با
$C_{ij}$
نشان می دهیم و به صورت زیر تعریف می کنیم:
$$C_{ij} = (-1)^{i+j} M_{ij}$$ 

توجه کنید که کهاد و همسازه یک درایه حداکثر تفاوتشان در یک علامت است.
$$C_{ij} = + M_{ij} \; \text{یا} \; -M_{ij}$$

 <b>مثال)</b>
 کهاد و همسازه درایه های 
$a_{12}, a_{33}$
را برای ماتریس زیر بدست آورید
$$
A=
\begin{bmatrix}
2&-1&5 \\
0&3&4 \\
2&2&-2 \\
\end{bmatrix}
$$

<b>حل:</b>
با بکارگیری تعریف اخیر داریم
  \begin{align*}
    M_{12} &= 
det \left( 
\begin{bmatrix}
0&4 \\
2&-2 \\
\end{bmatrix} \right) = 0 \times (-2) - (4 \times 2) = -8 \\
    C_{12} &= (-1)^{1+2} M_{12} = -1 \times -8 = 8 \\
    M_{33}&= det \left( 
\begin{bmatrix}
2&-1 \\
0&3 \\
\end{bmatrix} \right) = 2 \times 3 - (-1) \times 0 = 6 \\
    C_{33}&= (-1)^{3+3} M_{33} = 1 \times 6 = 6 \\
  \end{align*}

  دترمینان ماتریس مربعی A برابر است با مجموع حاصل ضرب درایه های هر سطر یا هر ستون در همسازه مربوط به آن درایه. بنابراین دترمینان ماتریس A برحسب  بسط سطر i
ام برابر است با
$$det(A)=a_{i1}C_{i1}+a_{i2}C_{i2}+\cdots+a_{in}C_{in}$$  

<b>مثال)</b>
مطلوب است محاسبه دترمینان ماتریس A برحسب
$$
A=
\begin{bmatrix}
1&0&3 \\
13&-2&5 \\
-1&1&0 \\
\end{bmatrix}
$$
سطر سوم:
$$(-1)^4 \times (-1) \times
det \left( 
\begin{bmatrix}
0&3 \\
-2&5 \\
\end{bmatrix} \right) + (-1)^5 \times 1 \times 
det \left( \begin{bmatrix}
1&3 \\
13&5 \\
\end{bmatrix} \right) = 28
$$

سطر دوم:
$$(-1)^3 \times 13 \times
det \left( \begin{bmatrix}
0&3 \\
1&0 \\
\end{bmatrix} \right) + (-1)^4 \times -2 \times 
det \left( \begin{bmatrix}
1&3 \\
-1&0 \\
\end{bmatrix} \right) + (-1)^5 \times 5 \times 
det \left( \begin{bmatrix}
1&0 \\
-1&1 \\
\end{bmatrix} \right) = 28
$$
ستون اول:
$$(-1)^2 \times 1 \times
det \left( \begin{bmatrix}
-2&5 \\
1&0 \\
\end{bmatrix} \right) + (-1)^3 \times 13 \times 
det \left( \begin{bmatrix}
0&3 \\
1&0 \\
\end{bmatrix} \right) + (-1)^4 \times -1 \times 
det \left( \begin{bmatrix}
0&3 \\
-2&5 \\
\end{bmatrix} \right) = 28
$$
ستون دوم:
$$(-1)^3 \times 0 + (-1)^4 \times -2 \times 
det \left( \begin{bmatrix}
1&3 \\
-1&0 \\
\end{bmatrix} \right) + (-1)^5 \times 1 \times 
det \left( \begin{bmatrix}
1&3 \\
13&5 \\
\end{bmatrix} \right) = 28
$$
<br>
چند خاصیت مهم از دترمینان ها:
1. $det(I)=1$
2. $det(A^T)=det(A)$
3. $det(AB)=det(A)det(B)$
4. $det(A^{-1}) = det(A)^{-1}$
5. $det(\alpha A) = α^n det(A)$

</div></font>

In [ ]:
a = np.array([ [5, 4], 
               [7, 10] ])

b = np.array([ [2, -1, 5],
               [0, 3, 4],
               [2, 2, -2] ])
c = np.identity(2)
aT = a.T

a_det = np.linalg.det(a)
b_det = np.linalg.det(b)


print('det(A): {}' .format(int(a_det)))
print('det(B): {}' .format(int(b_det)))

print('is det(I) = 1? -> {}' .format(np.linalg.det(c) == 1))
print('is det(AT) == det(A)? -> {}' .format(np.linalg.det(aT) == np.linalg.det(a)))

det(A): 21
det(B): -65
is det(I) = 1? -> True
is det(AT) == det(A)? -> True


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>4. اثر ماتریس ها</font>
<br>

<b>اثر</b>
 یک ماتریس که با نماد 
$trace(A)$
نمایش داده می شود، به صورت زیر است
$$trace(A)=\sum^{n}_{i=1} a_{ii}$$

خواص زیر برای اثر ماتریس ها برقرار است:
1. trace(A+B) = trace(A) + trace(B)
2. trace(α A) = α trace(A)
3. trace($A^T$) = trace(A)
4. trace(ABCD) = trace(BCDA) = trace(CDAB) = trace(ِDABC)

<br>

اگر A یک ماتریس 
$n \times n$
باشد، آنگاه عبارات زیر معادل هستند:

1. 
ماتریس A نامنفرد(ناتکین، معکوس پذیر) است
2. 
دترمینان ماتریس A مخالف صفر است
3. 
دستگاه
$AX=B$
به ازای هر b جواب منحصر به فرد دارد
4. 
$Rank(A)=n$
5. 
$AX=0$
جواب بدیهی صفر دارد
6. 
ماتریس A با ماتریس
$I_n$
هم ارز سطری است
7. 
ستون‎های ماتریس A مستقل خطی هستند
8. 
سطر‎های ماتریس A مستقل خطی هستند
9. 
$dim(N(A))=0$
10. 
مقادیر ویژه ماتریس A مخالف صفر هستند
11. 
یکتا جواب دستگاه
$X = A^{-1}B$
است.
12. 
$dim(R(A))=n$


ماتریس مربعی A را 
**مثبت معین**
 گوییم هرگاه برای هر بردار 
$X\neq 0$
داشته باشیم :
$$X^T(\frac{A+A^T}{2})X>0$$


**مثال)**
نشان دهید ماتریس داده شده مثبت معین است.
$A=\begin{bmatrix}
1&1\\0&1
\end{bmatrix}$

**حل)**
باید نشان دهیم برای هر 
$X=\begin{bmatrix}
x_1\\x_2
\end{bmatrix}\neq0$
داریم :
$X^T(\frac{A+A^T}{2})X>0$

ابتدا توجه داشته باشید که 
$$\frac{1}{2}(A+A^T)=\frac{1}{2}\left(\begin{bmatrix}
1&1\\0&1
\end{bmatrix}+\begin{bmatrix}
1&0\\1&1
\end{bmatrix}\right)=\frac{1}{2}\begin{bmatrix}
2&1\\1&2
\end{bmatrix}=\begin{bmatrix}
1 &\frac{1}{2}\\ \frac{1}{2}&1
\end{bmatrix}$$

از طرفی داریم:
$$
X^T(\frac{A+A^T}{2})X=[x_1 \; x_2 ]
\begin{bmatrix}
1&\frac{1}{2}\\
\frac{1}{2}&1
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2
\end{bmatrix}=[x_1 \; x_2]
\begin{bmatrix}
x_1+\frac{1}{2}x_2\\
\frac{1}{2}x_1+x_2
\end{bmatrix}
$$
$$=x_1^2+x_1x_2+x_2^2=\frac{1}{2}(x_1^2+x_2^2+(x_1+x_2)^2)>0$$
لذا ماتریس A مثبت معین است.


**توجه)**
در بیشتر موارد کاربردی برای مثبت معین بودن، ماتریس A متقارن است و لذا تعریف به صورت زیر خلاصه می‌شود.
$$A^T=A \Longrightarrow X^T(\frac{A+A^T}{2})X=X^T(\frac{A+A}{2})X=X^TAX > 0$$
بنابراین ماتریس متقارن A را مثبت معین گوییم هرگاه برای هر 
$X\neq0$
داشته باشیم : 
$$X^TAX>0$$

</div></font>




In [ ]:
a = np.array([ [5, 4], 
               [7, 10] ])

b = np.array([ [2, -1, 5],
               [0, 3, 4],
               [2, 2, -2] ])

a_trace = np.trace(a)
b_trace = np.trace(b)

print('trace(a): {}' .format(a_trace))
print('trace(b): {}' .format(b_trace))

trace(a): 15
trace(b): 3


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>5. نرم‎های برداری</font>
<br>

<b>فضای متریک یا متری</b>
 S به مجموعه ای گفته می شود که مفهومی از فاصله با تابع
$d:S \times S → \mathbf{R}$
با شرایط زیر بین اعضای آن تعریف شده باشد:

($x,y,z \in S$)

1. $d(x,y) ≥ 0$
2. $d(x,y) = 0 ⇔ x=y$
3. $d(x,y) = d(y,x)$
4. $d(x,z) \le d(x,y)+d(y,z)$


هر تابع به صورت
$\| \cdot \| : \mathbf{R}^n → \mathbf{R}^{+}$
که در خواص سه گانه
1. $\|X\|=0 ⇔ X=0 \qquad ∀X \in \mathbf{R}^{n}$
2. $\| \alpha X\|= |\alpha| \|X\| \qquad ∀α \in \mathbf{R}$
3. $\|X+Y\| \leq \|X\|+\|Y\| \qquad ∀X,Y \in \mathbf{R}^{n}$

صدق کند یک 
<b>نرم برداری</b>
 روی فضای برداری 
$\mathbf{R}^n$
نامیده می شود.

یکی از نرم های معروف نرم 
$\ell_2$
است که به صورت زیر تعریف می شود:

$$\|\mathbf{X}\|_2 = \sqrt{\sum_{i=1}^n x_i^2} = \langle \mathbf{X},\mathbf{X} ⟩ $$

یکی دیگر از نرم های معروف نرم 
$\ell_1$
است که به صورت زیر تعریف می شود:

$$\|\mathbf{X}\|_1 = \sum_{i=1}^n \left|x_i \right|.$$

<b>قضیه فیثاغورس)</b>
اگر X بر Y عمود باشد یا به طور معادل
$⟨ X,Y ⟩ = 0$
آنگاه
$$
\| \mathbf{X} + \mathbf{Y} \|_2^2 =  \| \mathbf{X} \|_2^2 +  \| \mathbf{Y} \|_2^2
$$

<b> نامساوی کشی-شوارتز)</b>
$$
| ⟨ X,Y ⟩ | \leq  \| \mathbf{X} \|_2   \| \mathbf{Y} \|_2
$$

در کاربردهایی از یادگیری ماشین و یادگیری عمیق به دنبال بیشینه کردن یا کمینه کردن فاصله بازنمایی‎هایی از دادهایمان هستیم مثلا کمینه کردن فاصله بین بازنمایی تصاویر یک فرد به ما در تشخیص چهره وی کمک می کند که در این موارد نرم‎ها به عنوان معیاری برای توصیف فاصله بردارها به ما کمک می کنند. 

تابع
$\|.\|:\mathbf{R}^{n\times n}\longrightarrow \mathbf{R} ^+$
 را یک نرم ماتریسی گوییم هرگاه در شرایط ۳ گانه زیر صدق کند.

 1. $ \|A\| \geq 0 , \|A\|=0 \iff A=0 \hspace{.2cm} \forall A \in \mathbf{R}^{n \times n}$
 2. $	\|\alpha A\|=|\alpha| \|A\|A \hspace{ .2cm} \forall \alpha \in \mathbf{R}$
 3. $ \|A+B\| \leq \|A\|+\|B\| \hspace{.3cm} \forall A,B \in \mathbf{R}^{n \times n}$

  توجه کنید خاصیت سوم همان نامساوی مثلث است  که البته گاهی اوقات به آن سازگاری جمعی هم گفته می‌شود.
 
   هر تابع 
 $\|.\|$
 که در خواص سه گانه بالا صدق کند یک نرم ماتریس خواهد بود. البته در کاربردها و آنالیز همگرایی روش‎ها اغلب  لازم است یک نرم ماتریسی خاصیت اضافی دیگری به صورت 
 $\|AB\|\leq\|A\|\|B\| \hspace{.3cm} (4)$
داشته باشد که به آن خاصیت ضربی گفته می‌شود.

بنابراین یک نرم ممکن است فقط در ۳ خاصیت گفته شده صدق کن و در خاصیت چهارم صدق نکند . اما همانطور که گفته شد اگر نرم ماتریسی که با آن کار می کنیم در خاصیت ضربی هم صدق کند بسیار مناسب و کاربردی تر خواهد بود. 	

اولین نرمی که ظاهراً تعمیم نرم ۲ برداری برای ماتریس‌هاست نرم فربنیوس است که به صورت 
$\|.\|_F$
نمایش داده می‌شود و برابر است با جذر مجموع مربعات درایه‌های ماتریس.
به راحتی می‌توان نشان داد که هر ۴ شکلی که برای نرم فربنیوس در ادامه آورده شده‌اند باهم معادل می‌باشند.

1. فرض کنید A ماتریسی 
$n\times n$
باشد آنگاه:
$$\|A\|_F=\sqrt{trace(A^TA)}=\sqrt{trace(AA^T)}$$

2. فرض کنید 
$A=(a_{ij})$
آنگاه:
$$\|A\|_F=\sqrt{\sum_{i=1}^{n}\sum_{j=1}^{n}\mid a_{ij}\mid ^2}$$

3. فرض کنید نمایش ستونی A به صورت 
$A=[a_1 \hspace{.2cm} a_2 \hspace{.2cm} ... \hspace{.2cm} a_n]$
باشد، آنگاه:
$$\|A\|_F=\sqrt{\sum_{i=1}^{n}\|a_i\|_2^2}$$

4. فرض کنید نمایش سطری A به صورت 
$A=\begin{bmatrix}
a'_1\\\vdots \\ a'_n
\end{bmatrix}$
باشد آنگاه:
$$\|A\|_F=\sqrt{\sum_{i=1}^{n}\|a'_i\|_2^2}$$


  دسته‌ای دیگر از نرم‎های ماتریسی که بر اساس یک نرم برداری به صورت 
 $$\|A\|=\max_{X\neq 0} \frac{\|AX\|}{\|X\|}$$
 ساخته می‌شوند را نرم القایی می‌نامیم. توجه کنید که دو نرم سمت راست رابطه‌ی فوق نرم برداری بوده و نرم سمت چپ رابطه بیانگر یک نرم ماتریسی است.

<b>مثال)</b>
با استفاده از تعریف، مقدار 
$\|A\|_1$
  را برای ماتریس 
  $A=\begin{bmatrix}
  0&-1\\2&0
  \end{bmatrix}$
  محاسبه کنید.

<b>حل)</b>
فرض کنید 
$X\in \mathbf{R}^2$
طوری باشد که 
$\|X\|_1=1$
یعنی اگر 
$X=\begin{bmatrix}
x_1\\x_2
\end{bmatrix}$
آنگاه 
$\mid x_1 \mid + \mid x_2 \mid =1 $
از طرفی داریم:
<br>

$$AX=\begin{bmatrix}
0&-1\\2&0
\end{bmatrix}\begin{bmatrix}
x_1\\x_2
\end{bmatrix}=\begin{bmatrix}
-x_2\\2x_1
\end{bmatrix}$$

بنابراین داریم :
$\|AX\|_1=\left \| \begin{bmatrix}
-x_2\\2x_1
\end{bmatrix} \right \|_1=\mid x_2 \mid + 2\mid x_1 \mid$
لذا داریم :
$$\|A\|_1=\max_{\|X\|_1=1}\|AX\|_1=\max_{\mid x_1 \mid + \mid x_2 \mid =1}\left \{ \mid x_2 \mid +2\mid x_1 \mid \right \}$$
مساله اخیر یک مساله بهینه‌سازی (ماکزیمم) غیر خطی (به دلیل وجود قدر مطلق در تابع هدف 
$|x_2|+2|x_1|$
)
مقید است. در واقع یک قید غیر خطی به صورت
$|x_1|+|x_2|=1$
مفروض است.
$$\max |x_2|+2|x_1|\hspace{5cm}$$
$$ s.t  \hspace{7cm} $$
$$|x_1|+|x_2|=1\hspace{5cm}$$
که حل آن را به خواننده واگذار می کنیم.

<b>قضیه)</b>
هرگاه 
$A$
یک ماتریس حقیقی 
$n\times n$
باشد، آنگاه برای نرم‌های ماتریس القایی داریم:

  $$(1)\quad ||A||_1=\max_{1\le j\le n}\sum_{i=1}^{n}
  |a_{ij}|$$
  
  $$(2)\quad ||A||_\infty=
  \max_{1\le i\le n}\sum_{j=1}^n
  |a_{ij}|$$

</div></font>

In [22]:
a = np.array([1, 5, 6, 15, 8, 4+2j, 0-7j, 11, 0+5j])
b = a.reshape(3, 3)

L1 = np.linalg.norm(a, 1)
L2 = np.linalg.norm(a, 2)
L_inf = np.linalg.norm(a, np.inf)
L_frobenius = np.linalg.norm(b, 'fro')

print('norm1(a): {}' .format(L1))
print('norm2(a): {}' .format(L2))
print('norm_inf(a): {}' .format(L_inf))
print('norm_frobenius(a): {}\n' .format(L_frobenius))


# calculate norms for matrix
X = np.array([ [-1, 0, 2],
               [0, 1, 3] ])
LM1 = np.max(np.sum(X, 0))
LM2 = np.max(np.sum(X, 1))
LMF = np.sqrt(np.trace(np.dot(X.T, X)))

print('norm1(X): {}' .format(LM1))
print('norm2(X): {}' .format(LM2))
print('norm_frobenius(X): {}' .format(LMF))



norm1(a): 62.47213595499958
norm2(a): 23.790754506740637
norm_inf(a): 15.0
norm_frobenius(a): 23.790754506740637

norm1(X): 5
norm2(X): 4
norm_frobenius(X): 3.872983346207417


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>6. تعریف عبارات سیمبولیک در پایتون</font>
<br>
مشابه با syms در متلب
</div></font>

In [ ]:
import sympy as sp

x = sp.symbols('x')
y = sp.symbols('y')

f = sp.sin(x) + sp.cos(y) + sp.tan(x)
y = f * 5

print(f)
print(y)

sin(x) + cos(y) + tan(x)
5*sin(x) + 5*cos(y) + 5*tan(x)


<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>7. تنسورها</font>
<br>
تنسورها تعمیمی از اسکالرها، بردارها و ماتریس ها برای ابعاد بالاتر از 2 هستند. 

</div></font>


<div>
<center>
<img src="https://www.kdnuggets.com/wp-content/uploads/scalar-vector-matrix-tensor.jpg" width="500">
</center>
</div>


<font face="Calibri" size=4><div dir=rtl>
فرض کنید عکسی سیاه و سفید (grayscale) در اختیار دارید در این صورت می توانید آن 
را در یک ماتریس ذخیره کنید. به این صورت که به هر پیکسل مقداری بین 0 تا 255 اختصاص دهید و در یک خانه ماتریس ذخیره کنید. در یادگیری ماشین و یادگیری عمیق عموما با داده‌ها با ابعاد بالا سر و کار داریم. به طور مثال برای ذخیره سازی یک عکس رنگی در فضای رنگی RGB نیاز به یک تنسور 3 بعدی داریم.همچنین برای نگهداری مجموعه ای از عکس‎ها به تنسور 4 بعدی نیاز داریم.
</div></font>


<div>
<center>
<img src="https://image.slidesharecdn.com/tensordecomposition-170301235239/95/a-brief-survey-of-tensors-5-638.jpg" width="500">
</center>
</div>


<font face="Calibri" size=4><div dir=rtl>
در ادامه یک تنسور سه بعدی تولید می کنیم
</div></font>

In [ ]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>7.1. عملیات روی تنسور‎ها</font>
<br>
ابتدا ضرب درایه‎ای (Hadamard product)
را معرفی می کنیم. فرض کنید
$\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times n}$
در این صورت داریم:
$$
\begin{split}\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.\end{split}
$$

مثال:

</div></font>

In [ ]:
A = np.arange(6, dtype=np.float32).reshape(2, 3)
B = A.copy()  # Assign a copy of `A` to `B` by allocating new memory
A * B

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)

<font face="Calibri" size=4><div dir=rtl>
<font color="red" size=5>منابع</font>
<br>

1. کتاب Introduction to Linear Algebra-Gilbert Strang
2. [داکیومنت های کتابخانه numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)



</div></font>